---

- hosts: data-generators
  gather_facts: False
  tasks:
    - name: stop data generators
      command: "killall datagen_multigrid.bash mggen_readouts"
      ignore_errors: True
      tags:
        - multigrid
