---

- hosts: data-generators
  gather_facts: False
  tasks:
    - name: stop data generators
      command: "killall datagen_NMX_overlap.bash udpgen_pcap"
      ignore_errors: True
      tags:
        - gdgem
