---

- hosts: packet-generator
  gather_facts: False
  tasks:
    - name: start packet generator
      command : "{{daemonize_cmd}} {{script_path}}/pktgen_fpga_config/rundemo"
      args:
        chdir: "{{script_path}}/pktgen_fpga_config/"
      become: True
      become_method: sudo
      tags:
        - generator
