---

- hosts: data-generators
  gather_facts: False
  tasks:
    - name: stop data generators
      command: "killall datagen_gdgem.bash nmxgen_apv"
      ignore_errors: True
      tags:
        - gdgem
