---
- hosts: sonde-gateway
  user: dgdaq
  gather_facts: False

  tasks:
    - name: start sonde readout
      shell: "/usr/bin/python /home/dgdaq/essproj/event-formation-unit/utils/sondectrl/ideasctrl.py -i 10.10.0.50 -c stop"
