---
- hosts: packet-generator
  gather_facts: False
  tasks:
    - name: stop carbon metrics collection
      command: "killall pktgen_carbon.bash"
      ignore_errors: True
      tags:
        - generator
