---
- hosts: sonde-gateway
  user: "{{ sonde_server_user }}"
  gather_facts: False
  tasks:
    - name: stop sonde gateway
      command: "killall udpredirect"
      ignore_errors: True
      tags:
        - sonde

- hosts: packet-generator
  gather_facts: False
  tasks:
    - name: stop carbon metrics collection
      command: "killall pktgen_carbon.bash"
      ignore_errors: True
      tags:
        - generator
