---
- hosts: sonde-gateway
  user: dmsc
  gather_facts: False
  tasks:
    - name: stop sonde gateway
      command: "killall gateway udprep"
      ignore_errors: True

- hosts: packet-generator
  gather_facts: False
  tasks:
    - name: stop carbon metrics collection
      command: "killall pktgen_carbon.bash"
      ignore_errors: True
