---

- hosts: sonde-gateway
  user: dmsc
  gather_facts: False
  tasks:
    - name: setup packet gateway for sonde
      command: "{{daemonize_cmd}} /home/dmsc/gateway"

- hosts: packet-generator
  gather_facts: False
  tasks:
    - name: start carbon metrics collection
      command: "{{daemonize_cmd}} {{script_path}}/pktgen_fpga_config/pktgen_carbon.bash"
