- name: executable is installed
  unarchive:
    remote_src: yes
    url: https://jenkins.esss.dk/dm/job/ess-dmsc/job/forward-epics-to-kafka/job/essiip-deployment/lastSuccessfulBuild/artifact/forward-epics-to-kafka-centos.tar.gz
    dest: "~"

- name: configuration file is installed
  copy:
    src: "config.json"
    dest: "~"
