# Check integration test results

- hosts: test-orchestrator
  tasks:
    - name: test result dir exists
      file:
        path: "{{ integration_test_result_dir }}"
        state: directory

- hosts: test-orchestrator
  any_errors_fatal: true
  tasks:
    - name: old NeXus file is absent
      file:
        path: "{{ integration_test_result_dir }}/{{ integration_test_nexus_file_name }}"
        state: absent

- hosts: kafka-to-nexus
  any_errors_fatal: true
  tasks:
    - name: copy file from kafka-to-nexus host
      fetch:
        src: "{{ kafka_to_nexus_data_dir }}/{{ integration_test_nexus_file_name }}"
        dest: "{{ integration_test_result_dir }}/"
        flat: yes

- hosts: test-orchestrator
  any_errors_fatal: true
  tasks:
    - name: check if NeXus file was generated
      shell: "{{ hdf5_install_dir }}/bin/h5ls {{ integration_test_result_dir }}/{{ integration_test_nexus_file_name }}"
      args:
        chdir: "{{ hdf5_install_dir }}"
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}:../lib"

    - name: check if NeXus file contains expected data
      shell: "{{ test_orchestrator_python_bin }} {{ test_orchestrator_script_dir }}/test-output-file.py {{ integration_test_result_dir }}/{{ integration_test_nexus_file_name }}"

- hosts: itesteventformationunit01.dm.esss.dk
  any_errors_fatal: true
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: cspec_pipeline_result.rc!=0

- hosts: itesteventformationunit02.dm.esss.dk
  any_errors_fatal: true
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: mesytec_pipeline_result.rc!=0

- hosts: itesteventformationunit03.dm.esss.dk
  any_errors_fatal: true
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: gdgem_pipeline_result.rc!=0
