# Check integration test results

- hosts: kafka-to-nexus
  any_errors_fatal: true
  tasks:
    - name: copy output NeXus file
      fetch:
        src: "~/kafka-to-nexus/{{ nexus_file_name }}"
        dest: "{{ test_result_dir }}/"
        flat: yes

- hosts: test-orchestrators
  any_errors_fatal: true
  tasks:
    - name: check if NeXus file was generated
      shell: "/opt/dm_group/usr/bin/h5ls {{ test_result_dir }}/{{ nexus_file_name }}"
      args:
        chdir: "~"
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

    - name: check if NeXus file contains expected data
      shell: "{{ python_bin }} ./test-output-file.py {{ test_result_dir }}/{{ nexus_file_name }}"
      args:
        chdir: "~"

- hosts: efus
  any_errors_fatal: true
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: cspec_pipeline_result.rc!=0

- hosts: epics-to-kafka-forwarders
  any_errors_fatal: true
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: epics_forwarder_result.rc!=0

- hosts: kafka-to-nexus
  any_errors_fatal: true
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: kafka_to_nexus_result.rc!=0
