# Prepare integration test environment and start system under test

- hosts: itesteventformationunit01.dm.esss.dk
  tasks:
    - name: start cspec pipeline
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./efu -d ../lib/mgcncs2 \
          -s 60 \
          -b {{ integration_test_kafka_bootstrap_servers }} \
          -a {{ integration_test_graylog_host }} \
          -g {{ integration_test_graphite_url }}"
      args:
        chdir: "{{ event_formation_unit_install_dir }}/event-formation-unit/bin"
      async: "{{ integration_test_max_async_timeout }}"
      poll: 0
      register: cspec_pipeline
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

    - name: wait for cspec pipeline initialisation
      pause:
        seconds: 5

    - name: load cspec calibration
      shell: "{{ event_formation_unit_install_dir }}/event-formation-unit/util/efushell/mgloadcal.py {{ event_formation_unit_data_dir }}/validruns_15"
      args:
        chdir: "{{ event_formation_unit_install_dir }}/event-formation-unit/bin"

- hosts: itesteventformationunit02.dm.esss.dk
  tasks:
    - name: start mgmesytec pipeline
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./efu -d ../lib/mgmesytec \
          -s 60 \
          -b {{ integration_test_kafka_bootstrap_servers }} \
          -a {{ integration_test_graylog_host }} \
          -g {{ integration_test_graphite_url }}"
      args:
        chdir: "{{ event_formation_unit_install_dir }}/event-formation-unit/bin"
      async: "{{ integration_test_max_async_timeout }}"
      poll: 0
      register: mesytec_pipeline
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

    - name: wait for mesytec pipeline initialisation
      pause:
        seconds: 5

- hosts: kafka-to-nexus
  tasks:
    - name: output NeXus file is absent
      become: yes
      file:
        path: "{{ kafka_to_nexus_data_dir }}/{{ integration_test_nexus_file_name }}"
        state: absent

- hosts: test-orchestrator
  tasks:
    - name: set initial value of EPICS PV
      shell: "\
        {{ epics_install_dir }}/bin/pvput testCounter 0; \
        sleep 1"
