# Stop system under test

- hosts: test-orchestrators
  tasks:
    - name: send stop command to file writer
      shell: "{{ python_bin }} ./send-stop-cmd.py itest03.dm.esss.dk"
      args:
        chdir: "~"

- hosts: epics-to-kafka-forwarders
  tasks:
    - name: kill epics-to-kafka-forwarder
      shell: pkill -2 forward-epics

    - name: check if epics-to-kafka-forwarder finished
      async_status:
        jid: "{{ epics_forwarder.ansible_job_id }}"
      register: epics_forwarder_result
      until: epics_forwarder_result.finished
      retries: "{{ num_retries }}"
      ignore_errors: yes

    - name: print epics-to-kafka-forwarder stdout
      debug:
        msg: "{{ epics_forwarder_result.stdout_lines }}"

    - name: print epics-to-kafka-forwarder stderr
      debug:
        msg: "{{ epics_forwarder_result.stderr_lines }}"

- hosts: efus
  tasks:
    - name: check if cspec pipeline finished
      async_status:
        jid: "{{ cspec_pipeline.ansible_job_id }}"
      register: cspec_pipeline_result
      until: cspec_pipeline_result.finished
      retries: "{{ num_retries }}"
      ignore_errors: yes

    - name: print cspec pipline stdout
      debug:
        msg: "{{ cspec_pipeline_result.stdout_lines }}"

    - name: print cspec pipline stderr
      debug:
        msg: "{{ cspec_pipeline_result.stderr_lines }}"

- hosts: kafka-to-nexus
  tasks:
    - name: check if file writer finished
      async_status:
        jid: "{{ kafka_to_nexus.ansible_job_id }}"
      register: kafka_to_nexus_result
      until: kafka_to_nexus_result.finished
      retries: "{{ num_retries }}"
      ignore_errors: yes

    - name: print file writer stdout
      debug:
        msg: "{{ kafka_to_nexus_result.stdout_lines }}"

    - name: print file writer stderr
      debug:
        msg: "{{ kafka_to_nexus_result.stderr_lines }}"
