# Run integration test commands

- hosts: test-orchestrators
  tasks:
    - name: send command to start writing events to file
      shell: "{{ python_bin }} ./send-start-cmd.py itest03.dm.esss.dk {{ nexus_file_name }}"
      args:
        chdir: "~"

- hosts: data-generators
  tasks:
    - name: start data generation
      shell: "\
        echo {{ item }}; \
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./mgcncsgenfile \
          -f ../../test-data/cncs_10_13.bin \
          -i 192.168.12.22"
      args:
        chdir: "~/output/bin"
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"
      # Hacked loop
      with_items:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
        - 36
        - 37
        - 38
        - 39
        - 40

- hosts: file-writers
  tasks:
    - name: change value of EPICS PV
      shell: "\
        pvput SQ:AMOR:DIMETIX:SimVal 0; \
        sleep 1; \
        pvput SQ:AMOR:DIMETIX:SimVal 1; \
        sleep 1; \
        pvput SQ:AMOR:DIMETIX:SimVal 2; \
        sleep 1"

- hosts: file-writers
  tasks:
    - name: wait for cspec pipeline to finish running
      pause:
        seconds: 10
