# Prepare integration test environment and start system under test

- hosts: all
  tasks:
    - name: get integration test start time
      shell: "date '+%Y-%m-%d %H:%M:%S'"
      register: integration_test_start_time

- hosts: itestkafka01.dm.esss.dk
  tasks:
    - name: kafka file writer commands log file is absent
      file:
        path: "~/kafka_filewriter_command.log"
        state: absent

    - name: start writing kafka file writer commands to file
      shell: "/opt/dm_group/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic filewriter_command > kafka_filewriter_command.log"
      args:
        chdir: "~"
      async: 600
      poll: 0

    - name: kafka file writer status log file is absent
      file:
        path: "~/kafka_filewriter_status.log"
        state: absent

    - name: start writing kafka file writer status to file
      shell: "/opt/dm_group/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic filewriter_status > kafka_filewriter_status.log"
      args:
        chdir: "~"
      async: 600
      poll: 0

- hosts: itesteventformationunit02.dm.esss.dk
  tasks:
    - name: start mgmesytec pipeline
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./efu -d ../modules/mgmesytec \
          -f ../config/ILL_mappings.json \
          -s 150 \
          -b {{ integration_test_kafka_bootstrap_servers }} \
          -a {{ integration_test_graylog_host }} \
          -g {{ integration_test_graphite_url }}"
      args:
        chdir: "{{ event_formation_unit_install_dir }}/event-formation-unit/bin"
      async: "{{ integration_test_max_async_timeout }}"
      poll: 0
      register: mesytec_pipeline
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

    - name: wait for mesytec pipeline initialisation
      pause:
        seconds: 5

- hosts: itesteventformationunit03.dm.esss.dk
  tasks:
    - name: start gdgem pipeline
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./efu -d ../modules/gdgem \
          --file {{ event_formation_unit_data_dir }}/nmx_config.json
          -s 150 \
          -b {{ integration_test_kafka_bootstrap_servers }} \
          -a {{ integration_test_graylog_host }} \
          -g {{ integration_test_graphite_url }}"
      args:
        chdir: "{{ event_formation_unit_install_dir }}/event-formation-unit/bin"
      async: "{{ integration_test_max_async_timeout }}"
      poll: 0
      register: gdgem_pipeline
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

    - name: wait for gdgem pipeline initialisation
      pause:
        seconds: 5

- hosts: kafka-to-nexus
  tasks:
    - name: output NeXus file is absent
      become: yes
      file:
        path: "{{ kafka_to_nexus_data_dir }}/{{ integration_test_nexus_file_name }}"
        state: absent

- hosts: test-orchestrator
  tasks:
    - name: set initial value of EPICS PV
      shell: "\
        {{ epics_install_dir }}/bin/pvput testCounter 0; \
        sleep 1"

- hosts: nicos
  tasks:
    - name: start NICOS service
      become: yes
      shell: "\
        /etc/init.d/nicos-system start; \
        sleep 1"
