- hosts: test-orchestrators
  any_errors_fatal: true
  tasks:
    - name: check if Kafka cluster is available
      command: "{{ python_bin }} check-kafka-available.py {{ kafka_broker_address }}"
      chdir: "~"

# Check if AMOR IOC is running

# Check if ChannelFinder is running
