# Stop system under test

- hosts: pipeline-data-generator
  tasks:
    - name: check if efu data generator finished
      async_status:
        jid: "{{ efu_generator.ansible_job_id }}"
      register: efu_generator_result
      until: efu_generator_result.finished
      retries: "{{ integration_test_num_retries }}"
      ignore_errors: yes

    - name: print efu data generator stdout
      debug:
        msg: "{{ efu_generator_result.stdout_lines }}"

    - name: print efu data generator stderr
      debug:
        msg: "{{ efu_generator_result.stderr_lines }}"

- hosts: nicos
  tasks:
    - name: send command to stop writing events to file
      shell: "{{ nicos_install_dir }}/stop_file_writer.sh"

- hosts: efu
  tasks:
    - name: wait for pipeline to finish processing data
      pause:
        seconds: 5

    - name: check efu pipeline for correct counter values
      shell: "{{ event_formation_unit_install_dir }}/event-formation-unit/util/efushell/verifymetrics.py {{ integration_test_efu_metrics_verification_string }}"
      register: efu_pipeline_counters_result
      ignore_errors: yes

    - name: print efu pipeline counter check stdout
      debug:
        msg: "{{ efu_pipeline_counters_result.stdout_lines }}"

    - name: print efu pipeline counter check stderr
      debug:
        msg: "{{ efu_pipeline_counters_result.stderr_lines }}"

    - name: stop efu pipeline
      command: pkill -2 efu

    - name: check if efu pipeline finished
      async_status:
        jid: "{{ efu_pipeline.ansible_job_id }}"
      register: efu_pipeline_result
      until: efu_pipeline_result.finished
      retries: "{{ integration_test_num_retries }}"
      ignore_errors: yes

    - name: print efu pipeline stdout
      debug:
        msg: "{{ efu_pipeline_result.stdout_lines }}"

    - name: print efu pipeline stderr
      debug:
        msg: "{{ efu_pipeline_result.stderr_lines }}"

- hosts: itestkafka01.dm.esss.dk
  tasks:
    # This command is not very robust, but pgrep did not work with the more
    # specific terms in the end of the long commands, such as filewriter_status.
    - name: stop kafka console consumers
      shell: "pkill -2 -u jenkins -f 'java'"
