# Check integration test results

# Make sure test result directory exists and is empty
- hosts: test-orchestrator
  tasks:
    - name: test result is absent
      file:
        path: "{{ integration_test_result_dir }}"
        state: absent

    - name: test result dir exists
      file:
        path: "{{ integration_test_result_dir }}"
        state: directory

- hosts: all
  tasks:
      - name: save log to file
        become: yes
        shell: "journalctl --no-pager --since='{{ integration_test_start_time.stdout }}' > /home/jenkins/{{ ansible_fqdn }}.log"

      - name: copy log file
        fetch:
          src: "/home/jenkins/{{ ansible_hostname }}.log"
          dest: "{{ integration_test_result_dir }}/"
          flat: yes

    - name: log file is absent
      become: yes
      file:
        path: "~/{{ ansible_hostname }}.log"
        state: absent

- hosts: kafka-to-nexus
  any_errors_fatal: true
  tasks:
    - name: copy file from kafka-to-nexus host
      fetch:
        src: "{{ kafka_to_nexus_data_dir }}/{{ integration_test_nexus_file_name }}"
        dest: "{{ integration_test_result_dir }}/"
        flat: yes

- hosts: test-orchestrator
  any_errors_fatal: true
  tasks:
    - name: check if NeXus file was generated
      shell: "{{ hdf5_install_dir }}/bin/h5ls {{ integration_test_result_dir }}/{{ integration_test_nexus_file_name }}"
      args:
        chdir: "{{ hdf5_install_dir }}"
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}:../lib"

    - name: check if NeXus file contains expected data
      shell: "{{ test_orchestrator_python_bin }} {{ test_orchestrator_script_dir }}/test-output-file.py {{ integration_test_result_dir }}/{{ integration_test_nexus_file_name }}"

- hosts: itesteventformationunit01.dm.esss.dk
  any_errors_fatal: true
  tasks:
    - name: fail test if pipeline failed
      fail:
        msg: playbook failed
      when: cspec_pipeline_result.rc!=0

- hosts: itesteventformationunit02.dm.esss.dk
  any_errors_fatal: true
  tasks:
    - name: fail test if pipeline failed
      fail:
        msg: playbook failed
      when: mesytec_pipeline_result.rc!=0

- hosts: itesteventformationunit03.dm.esss.dk
  any_errors_fatal: true
  tasks:
    - name: fail test if pipeline failed
      fail:
        msg: playbook failed
      when: gdgem_pipeline_result.rc!=0
