# Stop system under test

- hosts: test-orchestrator
  tasks:
    - name: send command to stop writing events to file
      shell: "{{ test_orchestrator_python_bin }} {{ test_orchestrator_script_dir }}/send-stop-cmd.py 192.168.12.109:9092"
      environment: "{{ centos_python3_env }}"

- hosts: efu
  tasks:
    - name: check if cspec pipeline finished
      async_status:
        jid: "{{ cspec_pipeline.ansible_job_id }}"
      register: cspec_pipeline_result
      until: cspec_pipeline_result.finished
      retries: "{{ integration_test_num_retries }}"
      ignore_errors: yes

    - name: print cspec pipline stdout
      debug:
        msg: "{{ cspec_pipeline_result.stdout_lines }}"

    - name: print cspec pipline stderr
      debug:
        msg: "{{ cspec_pipeline_result.stderr_lines }}"
