# Check integration test results

- hosts: test-orchestrators
  tasks:
    - name: check if NeXus file contains expected data
      shell: "{{ python_bin }} ./test-output-file.py {{ test_result_dir }}/{{ nexus_file_name }}"
      args:
        chdir: "~"

- hosts: area-detectors
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: area_detector_ioc_result.rc!=0

- hosts: efus
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: cspec_pipeline_result.rc!=0

- hosts: epics-to-kafka-forwarders
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: epics_forwarder_result.rc!=0

- hosts: file-writers
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: file_writer_result.rc!=0
