# Run integration test commands

- hosts: test-orchestrator
  tasks:
    - name: send command to start writing events to file
      shell: "{{ test_orchestrator_python_bin }} {{ test_orchestrator_script_dir }}/send-start-cmd.py itestkafka01.dm.esss.dk:9092 {{ kafka_to_nexus_data_dir }}/{{ integration_test_nexus_file_name }}"
      environment: "{{ centos_python3_env }}"

- hosts: pipeline-data-generator
  tasks:
    - name: start data generation
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./mgcncsgenfile \
          -f {{ event_formation_unit_data_dir }}/cncs_10_13.bin \
          -i 192.168.12.104"
      args:
        chdir: "{{ event_formation_unit_install_dir }}/event-formation-unit/bin"
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

- hosts: kafka-to-nexus
  tasks:
    - name: wait for cspec pipeline to finish running
      pause:
        seconds: 30
