# Stop system under test

- hosts: test-orchestrator
  tasks:
    - name: send command to stop writing events to file
      shell: "{{ test_orchestrator_python_bin }} {{ test_orchestrator_script_dir }}/send-stop-cmd.py {{ integration_test_kafka_bootstrap_servers }}"
      environment: "{{ centos_python3_env }}"

- hosts: itesteventformationunit02.dm.esss.dk
  tasks:
    - name: check for correct counter values
      shell: "{{ event_formation_unit_install_dir }}/event-formation-unit/util/efushell/verifymetrics.py efu.mgmesytec.rx_packets:114015 efu.mgmesytec.geometry_errors:0 efu.mgmesytec.events:227325"

- hosts: itesteventformationunit01.dm.esss.dk
  tasks:
    - name: check if cspec pipeline finished
      async_status:
        jid: "{{ cspec_pipeline.ansible_job_id }}"
      register: cspec_pipeline_result
      until: cspec_pipeline_result.finished
      retries: "{{ integration_test_num_retries }}"
      ignore_errors: yes

    - name: print cspec pipline stdout
      debug:
        msg: "{{ cspec_pipeline_result.stdout_lines }}"

    - name: print cspec pipline stderr
      debug:
        msg: "{{ cspec_pipeline_result.stderr_lines }}"

- hosts: itesteventformationunit02.dm.esss.dk
  tasks:
    - name: check if mesytec pipeline finished
      async_status:
        jid: "{{ mesytec_pipeline.ansible_job_id }}"
      register: mesytec_pipeline_result
      until: mesytec_pipeline_result.finished
      retries: "{{ integration_test_num_retries }}"
      ignore_errors: yes

    - name: print mesytec pipline stdout
      debug:
        msg: "{{ mesytec_pipeline_result.stdout_lines }}"

    - name: print mesytec pipline stderr
      debug:
        msg: "{{ mesytec_pipeline_result.stderr_lines }}"
