# Check external services

- hosts: test-orchestrator
  any_errors_fatal: true
  tasks:
    - name: check if Kafka cluster is available
      command: "{{ test_orchestrator_python_bin }} ./check-kafka-available.py {{ test_orchestrator_kafka_bootstrap_servers }}"
      args:
        chdir: "{{ test_orchestrator_script_dir }}"

    - name: check if AMOR IOC PV is available
      command: "{{ epics_install_dir }}/bin/pvget testCounter"
