# Run integration test commands

- hosts: nicos
  tasks:
    - name: send command to start writing events to file
      shell: "{{ nicos_install_dir }}/start_file_writer.sh"

- hosts: pipeline-data-generator
  tasks:
    - name: start efu data generation
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./{{ integration_test_efu_generator_bin }} \
          -f {{ integration_test_efu_generator_data_file }} \
          -i {{ integration_test_efu_generator_destination_ip }} \
          -t {{ integration_test_efu_generator_throttle }} \
          {{ integration_test_efu_generator_additional_args }}"
      args:
        chdir: "{{ event_formation_unit_install_dir }}/event-formation-unit/bin"
      async: "{{ integration_test_max_async_timeout }}"
      poll: 0
      register: efu_generator
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"
