# Run integration test commands

- hosts: test-orchestrator
  tasks:
    - name: send command to start writing events to file
      shell: "{{ python_bin }} ./send-start-cmd.py itest03.dm.esss.dk {{ integration_test_nexus_file_name }}"
      args:
        chdir: "~"

- hosts: pipeline-data-generator
  tasks:
    - name: start data generation
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./mgcncsgenfile \
          -f ../../test-data/cncs_10_13.bin \
          -i 192.168.12.22"
      args:
        chdir: "~/output/bin"
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

- hosts: kafka-to-nexus
  tasks:
    - name: wait for cspec pipeline to finish running
      pause:
        seconds: 30
