- hosts: test-orchestrators
  tasks:
    - name: test-results directory exists
      file:
        path: ~/test-results
        state: directory

- hosts: area-detectors
  tasks:
    - name: iocsh lock file remove cmd
      shell: rm -f require.lock-*
      args:
        chdir: "~"

    - name: start ioc
      shell: /usr/local/bin/procServ 12345 /opt/epics/modules/environment/2.0.0/3.15.4/bin/centos7-x86_64/iocsh ADPluginKafka_int_test.cmd
      args:
        chdir: "~"
      async: 150
      poll: 0
      register: area_detector_ioc

- hosts: efus
  tasks:
    - name: start cspec pipeline
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib:../lib ./efu2 -d cspec -s 60 -b itest02.dm.esss.dk:9092 -a 192.168.12.11 -g 192.168.12.31
      args:
        chdir: ~/output/bin
      async: 70
      poll: 0
      register: efu_pipeline

    - name: load cspec calibration
      shell: ./mgloadcal.py /home/jenkins/test-data/validruns_15
      args:
        chdir: ~/output/util/efushell

- hosts: epics-to-kafka-forwarders
  tasks:
    - name: start epics-to-kafka-forwarder
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib:./output/lib ./forward-epics-to-kafka --config-file config.json -v
      args:
        chdir: ~
      async: 150
      poll: 0

- hosts: file-writers
  tasks:
    - name: output NeXus file is absent
      file:
        path: ~/file-writer/output.h5
        state: absent

    - name: start file writer
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib ./kafka-to-nexus --broker-command //itest02.dm.esss.dk:9092
      args:
        chdir: ~/file-writer
      async: 150
      poll: 0

- hosts: test-orchestrators
  tasks:
    - name: send command to start writing events to file
      shell: ./send-start-cmd.py "itest03.dm.esss.dk" "output.h5"
      args:
        chdir: /home/jenkins

- hosts: data-generators
  tasks:
    - name: start data generation
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib:../lib ./gencspecfile -f ../../test-data/cncs_10_13.bin -i 192.168.12.22
      args:
        chdir: ~/output/bin

- hosts: file-writers
  tasks:
    - name: change value of EPICS PV
      shell: pvput SQ:AMOR:DIMETIX:LASER ON; sleep 1; pvput SQ:AMOR:DIMETIX:SimVal 0; sleep 1; pvput SQ:AMOR:DIMETIX:SimVal 1; sleep 1; pvput SQ:AMOR:DIMETIX:SimVal 2; sleep 1

- hosts: file-writers
  tasks:
    - name: wait for cspec pipeline to finish running
      pause:
        seconds: 30

- hosts: test-orchestrators
  tasks:
    - name: send stop command to file writer
      shell: ./send-stop-cmd.py "itest03.dm.esss.dk"
      args:
        chdir: /home/jenkins

- hosts: epics-to-kafka-forwarders
  tasks:
    - name: kill epics-to-kafka-forwarder
      shell: pkill -9 forward-epics

- hosts: efus
  tasks:
    - name: check cspec pipeline result
      async_status:
        jid: "{{ efu_pipeline.ansible_job_id }}"
      register: efu_pipeline_result
      until: efu_pipeline_result.finished
      retries: 30
      ignore_errors: yes

    - name: set playbook_result flag
      set_fact: playbook_result="success"

    - name: set playbook_result flag if task failed
      set_fact: playbook_result="failure"
      when: efu_pipeline_result.rc!=0

    - name: print task result
      debug:
        msg: "{{ efu_pipeline_result.stdout_lines }}"

- hosts: file-writers
  tasks:
    - name: check if NeXus file was generated
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib /opt/dm_group/usr/bin/h5ls output.h5
      args:
        chdir: ~/file-writer

    - name: copy output NeXus file
      fetch:
        src: ~/file-writer/output.h5
        dest: ~/test-results

- hosts: test-orchestrators
  tasks:
    - name: check if NeXus file contains expected data
      shell: ./test-output-file.py ./test-results/output.h5
      args:
        chdir: /home/jenkins

- hosts: area-detectors
  tasks:
    - name: stop ioc
      shell: pkill -f ADPluginKafka

- hosts: efus
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: playbook_result=="failure"
