- hosts: efus
  tasks:
    - name: start cspec pipeline
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib:../lib ./efu2 -d cspec -s 10 -b itest02.dm.esss.dk:9092 -a 192.168.12.11
      args:
        chdir: ~/output/bin
      async: 60
      poll: 0
      register: efu_pipeline

    - name: load cspec calibration
      shell: ./mgloadcal.py /home/jenkins/test-data/validruns_15
      args:
        chdir: ~/output/util/efushell

- hosts: file-writers
  tasks:
    - name: output NeXus file is absent
      file:
        path: ~/file-writer/output.h5
        state: absent

    - name: start file writer
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib ./kafka-to-nexus --broker-command //itest02.dm.esss.dk:9092
      args:
        chdir: ~/file-writer
      async: 60
      poll: 0

    - name: send start command to file writer
      shell: ./send-start-cmd.py "itest03.dm.esss.dk" "C-SPEC_detector" "c_spec_data" "output.h5"
      args:
        chdir: ~

- hosts: data-generators
  tasks:
    - name: start data generation
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib:../lib ./gencspecfile -f ../../test-data/cncs_10_13.bin -i 192.168.12.22
      args:
        chdir: ~/output/bin

- hosts: file-writers
  tasks:
    - name: send stop command to file writer
      shell: ./send-stop-cmd.py "itest03.dm.esss.dk"
      args:
        chdir: ~

# Check results
- hosts: efus
  tasks:
    - name: check cspec pipeline result
      async_status:
        jid: "{{ efu_pipeline.ansible_job_id }}"
      register: efu_pipeline_result
      until: efu_pipeline_result.finished
      retries: 30
      ignore_errors: yes

    - name:
      set_fact: playbook_result="failure"
      when: efu_pipeline.rc!=0

    - name: print task result
      debug:
        msg: "{{ efu_pipeline_result.stdout_lines }}"

    - name: check playbook result
      fail:
        msg: playbook failed
      when: playbook_result=="failure"
