- include: integration_test_env_check.yml
- include: integration_test_start_up.yml

- hosts: test-orchestrators
  tasks:
    - name: send command to start writing events to file
      shell: "{{ python_bin }} ./send-start-cmd.py itest03.dm.esss.dk {{ nexus_file_name }}"
      args:
        chdir: "~"

- hosts: data-generators
  tasks:
    - name: start data generation
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./mgcncsgenfile \
          -f ../../test-data/cncs_10_13.bin \
          -i 192.168.12.22"
      args:
        chdir: "~/output/bin"
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

- hosts: file-writers
  tasks:
    - name: change value of EPICS PV
      shell: "\
        pvput SQ:AMOR:DIMETIX:SimVal 0; \
        sleep 1; \
        pvput SQ:AMOR:DIMETIX:SimVal 1; \
        sleep 1; \
        pvput SQ:AMOR:DIMETIX:SimVal 2; \
        sleep 1"

- hosts: file-writers
  tasks:
    - name: wait for cspec pipeline to finish running
      pause:
        seconds: 30

- hosts: test-orchestrators
  tasks:
    - name: send stop command to file writer
      shell: "{{ python_bin }} ./send-stop-cmd.py itest03.dm.esss.dk"
      args:
        chdir: "~"

- hosts: epics-to-kafka-forwarders
  tasks:
    - name: kill epics-to-kafka-forwarder
      shell: pkill -9 forward-epics

- hosts: efus
  tasks:
    - name: check cspec pipeline result
      async_status:
        jid: "{{ cspec_pipeline.ansible_job_id }}"
      register: cspec_pipeline_result
      until: cspec_pipeline_result.finished
      retries: 30
      ignore_errors: yes

    - name: print cspec pipline stderr
      debug:
        msg: "{{ cspec_pipeline_result.stderr_lines }}"

- hosts: file-writers
  tasks:
    - name: check if NeXus file was generated
      shell: "/opt/dm_group/usr/bin/h5ls {{ nexus_file_name }}"
      args:
        chdir: "~/file-writer"
      environment:
        LD_LIBRARY_PATH: "{{ ld_library_path }}"

    - name: copy output NeXus file
      fetch:
        src: "~/file-writer/{{ nexus_file_name }}"
        dest: "{{ test_result_dir }}/"
        flat: yes

- hosts: test-orchestrators
  tasks:
    - name: check if NeXus file contains expected data
      shell: "{{ python_bin }} ./test-output-file.py {{ test_result_dir }}/{{ nexus_file_name }}"
      args:
        chdir: "~"

- hosts: area-detectors
  tasks:
    - name: stop ioc
      shell: pkill -f ADPluginKafka

- hosts: efus
  tasks:
    - name: check playbook result
      fail:
        msg: playbook failed
      when: cspec_pipeline_result.rc!=0
