- hosts: efus
  tasks:
    - name: start cspec pipeline
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib:../lib ./efu2 -d cspec -s 10 -b itest02.dm.esss.dk:9092 -a 192.168.12.11
      args:
        chdir: ~/output/bin
      async: 20
      poll: 0

    - name: load cspec calibration
      shell: ./mgloadcal.py ../data/g1w113
      args:
        chdir: ~/output/util/efushell

- hosts: file-writers
  tasks:
    - name: start file writer
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib ./kafka-to-nexus --broker-command //itest02.dm.esss.dk:9092
      args:
        chdir: ~/file-writer
      async: 20
      poll: 0

- hosts: data-generators
  tasks:
    - name: start data generation
      shell: LD_LIBRARY_PATH=/opt/dm_group/usr/lib:../lib ./gencspec -s 2 -t 100 -i 192.168.12.21
      args:
        chdir: ~/output/bin
